PREFIX dc-terms: <http://purl.org/dc/terms/>
DELETE { ?id0 dc-terms:identifier "01j82" .
    ?id0 a <https://www.example.org/kg/Person> .
    ?id0 <https://www.example.org/kg/hasName> ?name1 .
    ?id0 <https://www.example.org/kg/hasContact> ?contact .
    ?contact a <http://www.w3.org/2006/vcard/ns#Cell> .
    ?contact <http://www.w3.org/2006/vcard/ns#hasValue> ?number . }
WHERE { ?id0 dc-terms:identifier "01j82" .
    ?id0 a <https://www.example.org/kg/Person> .
    ?id0 <https://www.example.org/kg/hasName> ?name1 .
    ?id0 <https://www.example.org/kg/hasContact> ?contact .
    ?contact a <http://www.w3.org/2006/vcard/ns#Cell> .
    OPTIONAL { ?contact <http://www.w3.org/2006/vcard/ns#hasValue> ?number . } }