PREFIX cmns-dt: <https://www.omg.org/spec/Commons/DatesAndTimes/>
PREFIX dc-terms: <http://purl.org/dc/terms/>
PREFIX fibo-fnd-rel-rel: <https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?event_id ?previous_event_type ?iri ?id
WHERE {
  VALUES ?event_id { [target] }
  VALUES ?previous_event_type { [target] }

  ?event dc-terms:identifier ?event_id ;
    cmns-dt:succeeds* ?iri .
  ?iri dc-terms:identifier ?id ;
    fibo-fnd-rel-rel:exemplifies ?previous_event_type .
}
