PREFIX fibo-fnd-rel-rel: <https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cmns-col: <https://www.omg.org/spec/Commons/Collections/>
PREFIX cmns-dt: <https://www.omg.org/spec/Commons/DatesAndTimes/>
PREFIX cmns-dsg: <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-pts: <https://www.omg.org/spec/Commons/PartiesAndSituations/>
PREFIX dc-terms: <http://purl.org/dc/terms/>
PREFIX fibo-fbc-pas-fpas: <https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/>
PREFIX fibo-fnd-arr-lif: <https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/>
PREFIX fibo-fnd-dt-fd: <https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/>
PREFIX fibo-fnd-dt-oc: <https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/Occurrences/>
PREFIX ontoservice: <https://www.theworldavatar.com/kg/ontoservice/>

SELECT ?lifecycle_start_date ?lifecycle_end_date ?expire_stage ?order_event
WHERE {
  ?order_event fibo-fnd-rel-rel:exemplifies ontoservice:OrderReceivedEvent;
               ^cmns-col:comprises ?service_stage ;
               dc-terms:identifier "[target]" .
  
  ?service_stage cmns-dt:succeeds/cmns-pts:holdsDuring/cmns-dt:hasEndDate ?lifecycle_start_date ;
                 cmns-pts:holdsDuring/cmns-dt:hasEndDate ?lifecycle_end_date ;
                 ^cmns-dt:succeeds ?expire_stage .
                 
  ?service_stage fibo-fnd-dt-fd:hasSchedule/fibo-fnd-dt-fd:hasRecurrenceInterval/cmns-dt:hasDurationValue ?recurrence .
  FILTER(?recurrence = "P1D")
}