PREFIX person: <https://www.example.com/kg/person/>
PREFIX dc-terms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?dependent WHERE {
    # Uniquely identify the instance to be deleted
    ?iri a person:Person;
         dc-terms:identifier "[target]" .
    
    # Clauses for dependency
    {
        ?iri person:hasChild ?child_f ;
             a person:Father .
        BIND("Father of a child" AS ?dependent) # error message about the type of dependency
    } UNION {
        ?iri person:hasChild ?child_m ;
             a person:Mother .
        ?child_m person:hasName ?child_name .
        BIND(CONCAT("Mother of ", ?child_name) AS ?dependent) # error message about the exact dependent instance
    }
}