PREFIX cmns-col: <https://www.omg.org/spec/Commons/Collections/>
PREFIX dc-terms: <http://purl.org/dc/terms/>
PREFIX fibo-fbc-fi-ip: <https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/InstrumentPricing/>
PREFIX fibo-fbc-pas-fpas: <https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/>
PREFIX fibo-fnd-arr-lif: <https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/>
PREFIX fibo-fnd-rel-rel: <https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/>

SELECT DISTINCT ?obligation ?pricing
WHERE { 
  ?iri a fibo-fbc-pas-fpas:ContractLifecycleEventOccurrence;
    dc-terms:identifier "[target]";
    ^cmns-col:comprises/ ^fibo-fnd-arr-lif:hasStage/^fibo-fnd-arr-lif:hasLifecycle/fibo-fnd-rel-rel:confers ?obligation.
  OPTIONAL{
    ?obligation fibo-fnd-rel-rel:mandates ?pricing.
    ?pricing a fibo-fbc-fi-ip:PricingModel.
  }
}