PREFIX dc-terms: <http://purl.org/dc/terms/>
PREFIX ontochangelog: <https://theworldavatar.io/kg/ontochangelog/>

SELECT DISTINCT ?timestamp ?user ?activity WHERE { 
  ?iri a [target] ;
    dc-terms:identifier "[target]" .
  ?activity_instance a ?activity ; 
    ontochangelog:affected ?iri ;
    ontochangelog:timestamp ?timestamp .
  OPTIONAL{?activity_instance ontochangelog:wasPerformedBy/rdfs:label ?user}
}
ORDER BY ASC( ?timestamp )