PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX ser:   <https://theworldavatar.io/kg/service#>

SELECT DISTINCT ?endpoint
WHERE {
  ?service a ?service_type ;
    dcat:endpointURL ?endpoint .
  VALUES ?service_type { [target] }
}
