SELECT DISTINCT ?iri ?id ?field WHERE {
    ?iri a/rdfs:subClassOf* <http://example.com/Concept>.
    ?iri <http://example.com/propPath1>/<http://example.com/propPath2> ?field.
    BIND("01j82" AS ?id)
    ?iri <http://purl.org/dc/terms/identifier> "01j82".
}