SELECT DISTINCT ?iri ?id ?field WHERE {
    ?iri a/rdfs:subClassOf* <http://example.com/Concept>.
    ?iri <http://example.com/propPath1>/<http://example.com/propPath2> ?field.
    ?iri <http://purl.org/dc/terms/identifier> ?id.
    ?iri <http://example.com/addPath> ?addProperty.
}