SELECT DISTINCT ?iri ?id ?array_field ?field
WHERE { ?iri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> / <http://www.w3.org/2000/01/rdf-schema#subClassOf>* <http://example.com/Concept> .
    { ?iri <http://example.com/propPath1> ?group_test .
    ?group_test <http://example.com/propPath2> ?array_field .
    ?group_test <http://example.com/propPath2> ?field . }
    ?iri dc-terms:identifier ?id . }