SELECT DISTINCT ?iri ?id ?field ?addProperty WHERE {
    ?iri a <http://example.com/Concept>.
    ?iri <http://purl.org/dc/terms/identifier> ?id.
    ?iri <http://example.com/propPath1>/<http://example.com/propPath2> ?field.
    ?iri <http://example.com/addPath> ?addProperty.
}