SELECT DISTINCT ?iri ?field WHERE {
    ?iri a <http://example.com/Concept>.
    ?iri <http://example.com/propPath1>/<http://example.com/propPath2> ?field.
    FILTER REGEX(STR(?id), "(^|/|#)01j82$")
}