SELECT DISTINCT ?iri ?id ?parent_field WHERE {
    ?iri a/rdfs:subClassOf* <http://example.com/Concept>.
    ?iri <http://example.com/parentPath1> ?parent_field.
    ?parent_field <http://purl.org/dc/terms/identifier> "01j82".
    ?iri <http://purl.org/dc/terms/identifier> ?id.
}
