PREFIX sh: <http://www.w3.org/ns/shacl#>

CONSTRUCT {
  ?shape a sh:NodeShape; 
         sh:targetClass ?target;
         sh:rule ?ruleShape .
  ?ruleShape a ?ruleType;
               ?pred ?object.
}
WHERE {
  ?shape a sh:NodeShape ;
       sh:targetClass ?target;
       sh:targetClass [target];
       sh:node*/sh:rule ?ruleShape .
  ?ruleShape a ?ruleType ;
       ?pred ?object.
}
